### ISSUE TITLE
Adding Belkasoft to List of Forensic Tools

### ISSUE THREAD

**Issue by Chukanova** [JamesHabben/4n6-app-finder#54]
Hi James

Your Readme advises to submit an issue in case of new tools suggestions, so I hope I'm in the right place.

I would like to suggest including Belkasoft X in you app finder, because it supports quite a substantial amount of apps and can extract several hundreds of artifacts across mobile, computer and cloud sources. I am attaching a portion of Belkasoft X tech spec with a list of iOS supported apps. 
[iOS.pdf](https://github.com/JamesHabben/4n6-app-finder/files/13543311/iOS.pdf)
The tool overview can be found at https://belkasoft.com/x

Please let me know if it would be possible to submit a description and a full artifact list, and if so, what is required from my side.

Thank you.

**Comment by JamesHabben** [comment]
Hi @Chukanova,
I would love to add Belkasoft's tool to the database, but I don't have a license and I haven't been able to find any source available online to get the data. I have spoken to someone that works at Belkasoft, but I haven't been able to get any data from them yet. Is this PDF from the tool, or where did it come from?
